### ISSUE TITLE
After installation, the current plug-in can not be found

### ISSUE THREAD

**Issue by einsqing** [L3T/sentry-dingding#2]
After installation, the current plug-in can not be found

sentry：9.0.0

**Comment by NullYing** [comment]
在requirements.txt加入redis-py-cluster==1.3.4就能解决了

版本不兼容问题

**Comment by Alisa0026** [comment]
@NullYing 执行完安装在  /usr/lib/python2.7/site-packages/ 目录下，
我按照[sentry搭建过程]( https://blog.csdn.net/liuyueyi1995/article/details/53888312) 这个方式安装的sentry。
在onpremise目录下的requirements.txt加入redis-py-cluster==1.3.4

执行了
`pip install -r requirements.txt`
 `docker-compose restart 重启服务`
但是这个钉钉插件依然找不到为什么呢？

**Comment by NullYing** [comment]
@Alisa0026 请重新build

**Comment by Alisa0026** [comment]
@NullYing  redis-py-cluster==1.3.4 执行 docker-compose build时报错
![image](https://user-images.githubusercontent.com/13694317/44705021-fe86cf00-aacf-11e8-96ed-ad458746a32a.png)

然后我改成了 redis-py-cluster==1.3.5 build成功后，docker-compose restart 重启服务还是找不到插件

**Comment by NullYing** [comment]
因为redis-py-cluster版本不兼容问题才导致找不到插件，改为1.3.5就不需要加这个了

**Comment by Alisa0026** [comment]
@NullYing 试了半天1.3.4和1.3.5都找不到插件，心塞

**Comment by NullYing** [comment]
留意sentry启动时候的启动信息，docker-compose up启动，看看有没有什么错误

**Comment by NullYing** [comment]
tip: pip安装的并不是这个库的，建议用pip install git+https://github.com/L3T/sentry-dingding安装
